export enum Enums {
	UNIX_FORMAT = 'x',
	DISPLAY_DATE_FORMAT = 'MM/DD/YYYY HH:mm',
}

export enum DispatchLevel {
	DISPATCHED = 'DISPATCHED',
	PREASSIGNED = 'PREASSIGNED',
	UNDISPATCHED = 'UNDISPATCHED',
}

export enum VehicleArrivalTypes {
	ON_TIME = 'ON_TIME',
	LATE = 'LATE',
	VERY_LATE = 'VERY_LATE',
	FROM_DEPOT = 'FROM_DEPOT',
	FROM_PICKUP = 'FROM_PICKUP',
	FROM_DROPOFF = 'FROM_DROPOFF',
	FROM_VEHICLE_LOCATION = 'FROM_VEHICLE_LOCATION',
}
